### ISSUE TITLE
CardForm account number and exp date look broken

### ISSUE THREAD

**Issue by wunderlink** [lorensr/react-payment#1]
Trying to get this package up and running (it's just what I need!), but having a few issues.

If I just try to run the example (using "npm run storybook"), it launches the interface just fine. I then navigate to the CardForm example. Though entering text/numbers into most fields works fine, the "Account Number" and "MM / YY" fields don't work. 

The account number field does not take any input, attempts to type anything are ignored.
The MM / YY field allows me to enter any number 2 - 9 (resulting in 02, 03, etc). Entries of 1 or 0 are ignored. Attempts to enter the year just replace the month value.

I've tried this using several versions of node (4 - 6). This behavior occurs in the example as well as when the package is included in my project. 

Any ideas?

**Comment by lorensr** [comment]
What happens for you on 

http://lorensr.me/react-payment/?selectedKind=CardForm&selectedStory=full&full=0&down=1&left=1&panelRight=0

This works for me:

![image](https://cloud.githubusercontent.com/assets/251288/20125951/52d424cc-a5ff-11e6-8586-a94316bc0062.png)

**Comment by wunderlink** [comment]
Ah yea, I should have mentioned: that example works as expected for me

**Comment by lorensr** [comment]
Thanks for reporting, problem was a dep making some breaking change (not sure exactly what). Fixed in master and published v0.1.6

**Comment by wunderlink** [comment]
Awesome, thanks!! Much appreciated for the package!
